### ISSUE TITLE
Server terminates unexpectedly in Python 3

### ISSUE THREAD

**Issue by Natureshadow** [tk0miya/testing.mysqld#2]
I am using testing.mysqld in a database library test suite. It works really great (thanks for it!), but in Python 3 (not Python 2), the server terminates unexpectedly at the tearDown point. It also happens for the testing.postgresql module, so it is not strictly a MySQL issue, but I had to choose some place top file it.

You can find the test suite here: https://github.com/Veripeditus/OSMAlchemy/blob/master/test/test_util_db.py

In Python 2, everthing works well, but in Python 3, both mysqld and postgresql terminate unexpectedly somewhere near the end:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 774, in _reset
    self._reset_agent.rollback()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1563, in rollback
    self._do_rollback()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1601, in _do_rollback
    self.connection._rollback_impl()
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 670, in _rollback_impl
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 185, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 668, in _rollback_impl
    self.engine.dialect.do_rollback(self.connection)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/mysql/base.py", line 2542, in do_rollback
    dbapi_connection.rollback()
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 772, in rollback
    self._read_ok_packet()
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 746, in _read_ok_packet
    pkt = self._read_packet()
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 961, in _read_packet
    packet_header = self._read_bytes(4)
  File "/usr/lib/python3/dist-packages/pymysql/connections.py", line 998, in _read_bytes
    2013, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
ERROR
```

What I should probably add is that the data in the test database is *massive* - however, it works in Python 2, as I said.

**Comment by Natureshadow** [comment]
I actually got that solved.

It was my own mistake, the error only cleverly disguised that.

**Comment by RomHartmann** [comment]
> I actually got that solved.
> 
> It was my own mistake, the error only cleverly disguised that.

Would you _please_ elaborate on what said mistake was.
I mean, it's a long time ago, so memory might be a stretch at this point, so you'll just have to remember really hard.

For any other googlers, I moved all my database instantiation code from `setUp` to class level `setUpClass`.  
https://pypi.org/project/testing.mysqld/
https://docs.python.org/3/library/unittest.html#setupclass-and-teardownclass

```
MYSQLD_FACTORY = testing.mysqld.MysqldFactory(cache_initialized_db=True, port=7531)


class TestWhatever(unittest.TestCase):

    @classmethod
    def setUpClass(cls):
        cls.mysql = MYSQLD_FACTORY()
        cls.db_conn = create_engine(cls.mysql.url()).connect()

    def setUp(self):
        self.mysql.start()
        self.db_conn.execute("CREATE TABLE mytable")

    def tearDown(self):
        self.db_conn.execute("DROP TABLE mytable")

    @classmethod
    def tearDownClass(cls):
        cls.mysql.stop()

```

I should mention that this was an error that did _not_ cause a test failure, it's just awful noise.
